builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
    - freebsd
    - openbsd
    - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
    - goos: openbsd
      goarch: arm
    - goos: openbsd
      goarch: arm64
    - goos: freebsd
      goarch: arm64
    - goos: netbsd
      goarch: arm64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
